# Generated by Django 5.1.1 on 2025-04-22 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog1', '0003_post_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Author',
            new_name='author',
        ),
    ]
