# Generated by Django 5.1.1 on 2025-05-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog1', '0005_alter_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='myblog1.tag'),
        ),
    ]
